In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids, and separate the dataset:

In [2]:
from proj1_helpers import *
DATA_TRAIN_PATH = '../data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [3]:
DATA_TEST_PATH = '../data/test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [4]:
# We Separate the dataset
from implementations import *

tX_list, ids_list, y_list = separate_dataset(tX, ids, y, True)
tX_test_list, ids_test_list = separate_dataset(tX_test, ids_test) 

## Grid Search

In [39]:
function = ridge_regression
degree_vec = []
lambda_vec = []
for i in range(6):
    print('Dataset part {l}:'.format(l = i))
    rmse_te, BestDeg, BestLambda = grid_search(y_list[i], tX_list[i], function, True, degrees= range(1, 8))
    degree_vec.append(BestDeg)
    lambda_vec.append(BestLambda)
    print('     Best degree: {d}'.format(d = BestDeg))
    print('     Best lambda: {m}'.format(m = BestLambda))
    print('     Loss: {lo}'.format(lo = rmse_te))

Dataset part 0:
     Best degree: 1
     Best lambda: 1e-08
     Loss: 0.4271692619391528
Dataset part 1:
     Best degree: 1
     Best lambda: 1e-08
     Loss: 0.7909832423488046
Dataset part 2:
     Best degree: 3
     Best lambda: 0.0004641588833612782
     Loss: 0.5306821163024368
Dataset part 3:
     Best degree: 5
     Best lambda: 0.0027825594022071257
     Loss: 0.8233866880971475
Dataset part 4:
     Best degree: 3
     Best lambda: 0.0004641588833612782
     Loss: 0.5510419519754712
Dataset part 5:
     Best degree: 4
     Best lambda: 0.016681005372000592
     Loss: 0.789411151522702


In [40]:
weights_list = []
loss_list = []
mat_tX_test_list = []

for i in range(6):
    mat_tX, mat_tX_test = build_poly_log(tX_list[i], degree_vec[i], True, tX_test_list[i])
    w, l = ridge_regression(y_list[i], mat_tX, lambda_vec[i])
    weights_list.append(w)
    loss_list.append(l)
    mat_tX_test_list.append(mat_tX_test)
    

## Gradient Descent

In [ ]:
# Linear regression using gradient descent

initial_w = np.zeros(tX.shape[1])
max_iters = 50
gamma = 3e-7

weights, loss = least_squares_GD(y, tX, initial_w, max_iters, gamma)

## Least squares

In [76]:
# Least squares regression using normal equation
weights, loss = least_squares(y, tX)
loss

0.3396868094770349

## Ridge regression

In [9]:
# Ridge regression using normal equations
lambda_ = 1e-3
weights, loss = ridge_regression(y, tX, lambda_)
loss

(30,)

In [59]:
# Ridge regression with data augmentation
lambda_ = 1e-3
mat_tX = build_poly(tX, 5)
weights, loss = ridge_regression(y, mat_tX, lambda_)

loss

0.2967432202164457

In [35]:
# Ridge regression with separated data
lambda_ = 1e-3
weights_list, loss_list = separated_train(tX_list, y_list, ridge_regression, lambda_)

In [76]:
# Ridge regression on separated datset with data augmentation
lambda_ = 1e-3
mat_tX_list = build_poly_separated(tX_list, 3)
# weights, loss = ridge_regression(y_list[0], mat_tX_list[0], lambda_)

weights_list, loss_list = separated_train(mat_tX_list, y_list, ridge_regression, lambda_)

## Logistic regression

In [5]:
degrees = range(1, 2)
lambdas = np.logspace(-3, 0, 2)
gammas = np.logspace(-3, 0, 2)

degree_vec = []
lambda_vec = []
gamma_vec = []

for i in range(6):
    rmse_te, BestDeg, BestLambda, BestGamma = grid_search_for_log_reg(y_list[i], tX_list[i], True, 4, degrees, lambdas, gammas)
    degree_vec.append(BestDeg)
    lambda_vec.append(BestLambda)
    gamma_vec.append(BestGamma)
    print(rmse_te)



0.6743518202894218
0.6760595782127253
Done Lambda
0.27460595102616286
55.52095918305916
Done Lambda
Done Gamma
Done Deg
(array([0]), array([1]), array([0]))
0.27460595102616286
0.6904820795554201
0.6906967527802129
Done Lambda
0.8350689993549294
47.178291074990256
Done Lambda
Done Gamma
Done Deg
(array([0]), array([0]), array([0]))
0.6904820795554201
0.6771572514460912
0.6786088829898362
Done Lambda
0.367663662672965
65.29571120023466
Done Lambda
Done Gamma
Done Deg
(array([0]), array([1]), array([0]))
0.367663662672965
0.6921816360332991
0.6922447204470084
Done Lambda
0.7839173061584752
65.10496616960559
Done Lambda
Done Gamma
Done Deg
(array([0]), array([0]), array([0]))
0.6921816360332991
0.6800567321933159
0.6812274734114628
Done Lambda
0.5220848137763971
79.161281894291
Done Lambda
Done Gamma
Done Deg
(array([0]), array([1]), array([0]))
0.5220848137763971
0.6935768369329353
0.6934934912963826
Done Lambda
0.8900831232574502
73.9178254988596
Done Lambda
Done Gamma
Done Deg
(array([

In [49]:
#Log Reg Pen


degree_vec = [1]
lambda_vec = [1e-04]
gamma_vec = [5e-1]

weights_list = []
loss_list = []
mat_tX_test_list = []
max_iter= 10000

for i in range(6):
    print("loop")
    mat_tX, mat_tX_test = build_poly_log(tX_list[i], degree_vec[0], True, tX_test_list[i])
    initial_w = np.zeros((mat_tX.shape[1], 1))
    l, w = logistic_regression_penalized_gradient_descent(y_list[i], mat_tX, initial_w, max_iter, gamma_vec[0], lambda_vec[0])
    print(l)
    weights_list.append(w)
    loss_list.append(l)
    mat_tX_test_list.append(mat_tX_test)

loop
0.17199737533929327
loop
0.4539822967691729
loop
0.24545308205379776
loop
0.5672153191167804
loop
0.2572019773477076
loop
0.5363460013415859


In [8]:
weights_list = []
loss_list = []
mat_tX_test_list = []
max_iter = 5000

for i in range(3):
    print("loop")
    mat_tX, mat_tX_test = build_poly_log(tX_list[i], degree_vec[i], True, tX_test_list[i])
    initial_w = np.zeros((mat_tX.shape[1], 1))
    l, w = logistic_regression_penalized_gradient_descent(y_list[i], mat_tX, initial_w, max_iter, gamma_vec[i], lambda_vec[i])
    print(l)
    weights_list.append(w)
    loss_list.append(l)
    mat_tX_test_list.append(mat_tX_test)

0.1


## Generate predictions and save ouput in csv format for submission:

In [ ]:
# Data augmentation
OUTPUT_PATH = 'result.csv' # TODO: fill in desired name of output file for submission
mat_tX_test = build_poly(tX_test, 3)
print(mat_tX_test.shape)
y_pred = predict_labels(weights, mat_tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

In [41]:
# Separated dataset
OUTPUT_PATH = 'result.csv' # TODO: fill in desired name of output file for submission

tX_test_list, ids_test_list = separate_dataset(tX_test, ids_test)
y_pred_list = separated_eval(weights_list, tX_test_list)

y_pred = np.concatenate((y_pred_list[0], y_pred_list[1], y_pred_list[2], y_pred_list[3]))
ids_test_sub = np.concatenate((ids_test_list[0], ids_test_list[1], ids_test_list[2], ids_test_list[3]))

create_csv_submission(ids_test_sub, y_pred, OUTPUT_PATH)

In [12]:
# Data augmentation and separated dataset
OUTPUT_PATH = 'result.csv' # TODO: fill in desired name of output file for submission

tX_test_list, ids_test_list = separate_dataset(tX_test, ids_test)   #separate dateset

mat_tX_test_list = []

# for i in range(4):
#     print(i)
#     mat_tX_test = build_poly(tX_test_list[i], degree_vec[i])
#     mat_tX_test_list.append(mat_tX_test)

# mat_tX_test_list = build_poly_separated(tX_test_list, 3)            #data augmentation
y_pred_list = separated_eval(weights_list, mat_tX_test_list)        #prediction

y_pred = np.concatenate((y_pred_list[0], y_pred_list[1], y_pred_list[2], y_pred_list[3]))
ids_test_sub = np.concatenate((ids_test_list[0], ids_test_list[1], ids_test_list[2], ids_test_list[3]))

create_csv_submission(ids_test_sub, y_pred, OUTPUT_PATH)

0
1
2
3


## Prediction

In [50]:
# Eval

y_pred_list = separated_eval(weights_list, mat_tX_test_list, True) 

y_pred = np.concatenate((y_pred_list[0], y_pred_list[1], y_pred_list[2], y_pred_list[3], y_pred_list[4], y_pred_list[5]))
ids_test_sub = np.concatenate((ids_test_list[0], ids_test_list[1], ids_test_list[2], ids_test_list[3], ids_test_list[4], ids_test_list[5]))

OUTPUT_PATH = 'result.csv'
create_csv_submission(ids_test_sub, y_pred, OUTPUT_PATH)