In [2]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [3]:
from proj1_helpers import *
from implementations import *
DATA_TRAIN_PATH = '../data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

## Do your thing crazy machine learning thing here :) ...

In [4]:
x, y_ = zip(*[(tX[i], y[i]) for i in range(tX.shape[0]) if tX[i,22] >1 ])
x, y_ = np.array(x), np.array(y_)

In [5]:
y_

array([ 1., -1.,  1., ..., -1.,  1., -1.])

In [6]:
x[:,22]

array([2., 3., 2., ..., 3., 3., 2.])

In [8]:
x.shape[0]

72543

In [23]:
for i in range(x.shape[1]):
    if i != 22:
        x = np.c_[x, x[:,i]**2]
        x = np.c_[x, x[:,i]**3]
        x = np.c_[x, x[:,i]**4]
        x = np.c_[x, np.log(x[:,i])]

x = np.where(x==-999, np.nan, x) 
x = x[not x.isnan()]

/tmp/ipykernel_561938/3142681196.py:6: RuntimeWarning: invalid value encountered in log
  x = np.c_[x, np.log(x[:,i])]
/tmp/ipykernel_561938/3142681196.py:6: RuntimeWarning: divide by zero encountered in log
  x = np.c_[x, np.log(x[:,i])]


In [24]:
x.shape

(72543, 296)

In [27]:
x

array([[ 1.38470000e+02,  5.16550000e+01,  9.78270000e+01, ...,
         2.13750084e+12,  2.75343645e+16,  9.46355281e+00],
       [ 8.97440000e+01,  1.35500000e+01,  5.91490000e+01, ...,
         5.27520772e+13,  1.97842422e+18,  1.05322081e+01],
       [ 1.48754000e+02,  2.88620000e+01,  1.07782000e+02, ...,
         3.38730119e+13,  1.09598620e+18,  1.03845466e+01],
       ...,
       [-9.99000000e+02,  3.80830000e+01,  7.49970000e+02, ...,
         7.11655581e+13,  2.94912476e+18,  1.06320100e+01],
       [ 1.30075000e+02,  3.91800000e+00,  6.67810000e+01, ...,
         2.65137294e+16,  7.90607798e+21,  1.26054797e+01],
       [ 2.17020000e+02,  4.71560000e+01,  6.28240000e+01, ...,
         2.79209297e+13,  8.47045035e+17,  1.03201326e+01]])

In [26]:
# Linear regression using gradient descent

initial_w = np.zeros(x.shape[1])
max_iters = 150
gamma = 0.085

weights, loss = least_squares_GD(y_, standardize(x), initial_w, max_iters, gamma)

Gradient Descent(0/149): loss=nan
Gradient Descent(1/149): loss=nan
Gradient Descent(2/149): loss=nan
Gradient Descent(3/149): loss=nan
Gradient Descent(4/149): loss=nan
Gradient Descent(5/149): loss=nan
Gradient Descent(6/149): loss=nan
Gradient Descent(7/149): loss=nan
Gradient Descent(8/149): loss=nan
Gradient Descent(9/149): loss=nan
Gradient Descent(10/149): loss=nan
Gradient Descent(11/149): loss=nan
Gradient Descent(12/149): loss=nan
Gradient Descent(13/149): loss=nan
Gradient Descent(14/149): loss=nan
Gradient Descent(15/149): loss=nan
Gradient Descent(16/149): loss=nan
Gradient Descent(17/149): loss=nan
Gradient Descent(18/149): loss=nan
Gradient Descent(19/149): loss=nan
Gradient Descent(20/149): loss=nan
Gradient Descent(21/149): loss=nan
Gradient Descent(22/149): loss=nan
Gradient Descent(23/149): loss=nan
Gradient Descent(24/149): loss=nan
Gradient Descent(25/149): loss=nan
Gradient Descent(26/149): loss=nan
Gradient Descent(27/149): loss=nan
Gradient Descent(28/149): loss

In [ ]:
# Least squares regression using normal equation
weight, loss = least_squares(y, tX)
loss

In [29]:
# Ridge regression using normal equations
lambda_ = 1e-3
weight, loss = ridge_regression(y_, x, lambda_)
loss

/home/main/Documents/cours/ml/ml-project-1-pml/scripts/implementations.py:79: RuntimeWarning: invalid value encountered in matmul
  w = np.linalg.solve(tx.T @ tx + lambda_pr * np.eye(tx.shape[1]), tx.T @ y)


nan

## Generate predictions and save ouput in csv format for submission:

In [30]:
DATA_TEST_PATH = '../data/test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [31]:
OUTPUT_PATH = 'result.csv' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

ValueError: shapes (568238,30) and (296,) not aligned: 30 (dim 1) != 296 (dim 0)